#!/usr/bin/env bash
#
# End-to-end verification runner — frontend-auth-ui, Phase 8.
#
# Replaces what the SDD called "Phase 8, manual verification" with two
# automated suites, both run against the ONLY topology this project ships:
#
#     SPA  http://localhost:5173   (npm run preview, NOT vite dev)
#       │  built with VITE_API_BASE_URL=http://localhost:3000
#       ▼
#     API  http://localhost:3000   (the Spring Boot fat jar)
#
# THE TOPOLOGY IS THE POINT. `vite dev` proxies /api and makes the SPA
# same-origin with the backend — the one topology that never ships (Engram
# discovery #926: portable/POSIX is :5173 -> :3000, Docker is :8080 -> :3000).
# Under `vite dev` a green run proves nothing about `Origin` checking,
# `SameSite`, or the bootstrap admission path, which is exactly the blind spot
# that got a broken `Sec-Fetch-Site: same-origin` mechanism recommended in the
# first place. Both suites assert their own topology and fail loudly if they
# ever find themselves same-origin.
#
# ── Usage ───────────────────────────────────────────────────────────────────
#
#   tests/e2e/run-e2e.sh              # everything: backend + preview + both suites
#   tests/e2e/run-e2e.sh --api        # layer 1 only (pytest, tests/e2e/)
#   tests/e2e/run-e2e.sh --browser    # layer 2 only (Playwright, frontend/e2e/)
#   tests/e2e/run-e2e.sh --no-build   # reuse scraper/target/*.jar and frontend/dist
#   tests/e2e/run-e2e.sh --keep-up    # leave backend + preview running afterwards
#
# Everything it starts, it stops (EXIT trap) unless --keep-up is passed.
#
# ── Prerequisites ───────────────────────────────────────────────────────────
#
#   * PostgreSQL reachable at $DATABASE_URL (scripts/dev-db.sh up).
#   * The backend fat jar at scraper/target/fashion-scraper-1.0.0.jar
#     (mvn -f scraper/pom.xml -DskipTests package), or pass --no-build after
#     one build.
#   * Node >= 22 and `npm ci` already run in frontend/.
#   * For --browser: `npx playwright install chromium` once.
#
# ── Secrets ─────────────────────────────────────────────────────────────────
#
# NOTHING is hardcoded here. On first run this generates AUTH_JWT_SECRET, the
# e2e bootstrap-admin password and the CLI service-account password, and stores
# them in tests/e2e/.e2e-secrets.env (gitignored, mode 600). Later runs reuse
# that file — they have to: AdminSeeder never overwrites an existing password
# hash, so a fresh random password on run 2 would simply not be the account's
# password. Delete the file only together with the `e2e-admin` row.
#
# The bootstrap admin is `e2e-admin`, deliberately NOT the installation's own
# `admin`: seeding a username that already exists is a silent no-op, and this
# runner would then be logging in with a password nobody set.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
SECRETS_FILE="$REPO_ROOT/tests/e2e/.e2e-secrets.env"

API_ORIGIN="${E2E_API_BASE_URL:-http://localhost:3000}"
APP_ORIGIN="${E2E_APP_ORIGIN:-http://localhost:5173}"
API_PORT="${API_ORIGIN##*:}"
APP_PORT="${APP_ORIGIN##*:}"

RUN_API=1
RUN_BROWSER=1
DO_BUILD=1
KEEP_UP=0

for arg in "$@"; do
  case "$arg" in
    --api)      RUN_BROWSER=0 ;;
    --browser)  RUN_API=0 ;;
    --no-build) DO_BUILD=0 ;;
    --keep-up)  KEEP_UP=1 ;;
    -h|--help)  sed -n '2,50p' "${BASH_SOURCE[0]}"; exit 0 ;;
    *) echo "unknown flag: $arg" >&2; exit 2 ;;
  esac
done

say() { printf '\n\033[1;36m▸ %s\033[0m\n' "$*"; }
die() { printf '\n\033[1;31m✗ %s\033[0m\n' "$*" >&2; exit 1; }

# ── The topology assumption, asserted before anything starts ────────────────
[ "$API_ORIGIN" != "$APP_ORIGIN" ] || die \
  "E2E_API_BASE_URL and E2E_APP_ORIGIN are the same origin ($API_ORIGIN).
   These suites exist to exercise the CROSS-ORIGIN topology this project
   actually ships. A same-origin run cannot fail the way production fails."

# ── Secrets: reuse or mint ──────────────────────────────────────────────────
if [ ! -f "$SECRETS_FILE" ]; then
  say "minting tests/e2e/.e2e-secrets.env (first run)"
  umask 077
  {
    echo "# Generated by tests/e2e/run-e2e.sh. Gitignored. Never commit."
    echo "AUTH_JWT_SECRET=$(head -c 48 /dev/urandom | base64 | tr -d '\n=/+')"
    echo "ADMIN_BOOTSTRAP_USERNAME=e2e-admin"
    echo "ADMIN_BOOTSTRAP_PASSWORD=$(head -c 24 /dev/urandom | base64 | tr -d '\n=/+')"
    echo "CLI_SERVICE_ACCOUNT_USERNAME=e2e-cli-service"
    echo "CLI_SERVICE_ACCOUNT_PASSWORD=$(head -c 24 /dev/urandom | base64 | tr -d '\n=/+')"
  } > "$SECRETS_FILE"
  chmod 600 "$SECRETS_FILE"
fi
# shellcheck disable=SC1090
set -a; . "$SECRETS_FILE"; set +a

export DATABASE_URL="${DATABASE_URL:-jdbc:postgresql://127.0.0.1:5432/scraper}"
export DATABASE_USERNAME="${DATABASE_USERNAME:-postgres}"
export DATABASE_PASSWORD="${DATABASE_PASSWORD-}"
export APP_CORS_ALLOWED_ORIGINS="${APP_CORS_ALLOWED_ORIGINS:-$APP_ORIGIN}"
export SCRAPER_MODELS_ROOT="${SCRAPER_MODELS_ROOT:-$REPO_ROOT/scraper/_models}"
export PASSWORD_RESET_CHANNEL=console
export PASSWORD_RESET_LINK_BASE="$APP_ORIGIN"
export LOG_DIR="$REPO_ROOT/tests/e2e/.run/logs"

# The suites read these; they never guess a port or a credential.
export E2E_API_BASE_URL="$API_ORIGIN"
export E2E_APP_ORIGIN="$APP_ORIGIN"
export E2E_ADMIN_USERNAME="$ADMIN_BOOTSTRAP_USERNAME"
export E2E_ADMIN_PASSWORD="$ADMIN_BOOTSTRAP_PASSWORD"
export E2E_BACKEND_LOG="$LOG_DIR/scraper.log"

RUN_DIR="$REPO_ROOT/tests/e2e/.run"
mkdir -p "$LOG_DIR"

BACKEND_PID=""
PREVIEW_PID=""
cleanup() {
  local code=$?
  if [ "$KEEP_UP" = "1" ]; then
    say "--keep-up: backend pid ${BACKEND_PID:-none}, preview pid ${PREVIEW_PID:-none} left running"
    return $code
  fi
  [ -n "$BACKEND_PID" ] && kill "$BACKEND_PID" 2>/dev/null || true
  # `npm run preview` is a WRAPPER: it spawns vite as a child of its own.
  # Killing the wrapper alone reparents vite to init, the port stays bound, and
  # the NEXT run reads that as "already up" and silently tests against whatever
  # stale bundle the orphan is still serving. So the whole process GROUP goes —
  # which is why the preview is started under `setsid` below, and why the group
  # is signalled BEFORE the leader, not after (once the leader is gone there is
  # nothing left to look its children up by).
  if [ -n "$PREVIEW_PID" ]; then
    kill -TERM -- "-$PREVIEW_PID" 2>/dev/null || kill "$PREVIEW_PID" 2>/dev/null || true
  fi
  wait 2>/dev/null || true
  return $code
}
trap cleanup EXIT

wait_for() { # url, label, seconds
  local url="$1" label="$2" secs="${3:-90}" i=0
  while [ "$i" -lt "$secs" ]; do
    if curl -sf -o /dev/null "$url"; then say "$label is up"; return 0; fi
    i=$((i + 1)); sleep 1
  done
  die "$label never came up at $url (see $RUN_DIR/)"
}

port_busy() { (exec 3<>"/dev/tcp/127.0.0.1/$1") 2>/dev/null; }

# ── Backend ─────────────────────────────────────────────────────────────────
JAR="$REPO_ROOT/scraper/target/fashion-scraper-1.0.0.jar"
if port_busy "$API_PORT"; then
  say "port $API_PORT already bound — reusing whatever is listening there"
else
  [ -f "$JAR" ] || die "no jar at $JAR — run: mvn -f scraper/pom.xml -DskipTests package"
  say "starting backend on $API_ORIGIN (log: $E2E_BACKEND_LOG)"
  # JRE 21 runs the jar on this machine; JDK 24 only compiles it (CONTRIBUTING.md).
  JAVA_BIN="${E2E_JAVA_BIN:-/usr/lib/jvm/java-21-openjdk-amd64/bin/java}"
  [ -x "$JAVA_BIN" ] || JAVA_BIN="$(command -v java)"
  "$JAVA_BIN" -jar "$JAR" > "$RUN_DIR/backend.out" 2>&1 &
  BACKEND_PID=$!
  wait_for "$API_ORIGIN/" "backend" 120
fi

# ── Frontend preview ────────────────────────────────────────────────────────
if [ "$RUN_BROWSER" = "1" ]; then
  if port_busy "$APP_PORT"; then
    say "port $APP_PORT already bound — reusing whatever is listening there"
  else
    if [ "$DO_BUILD" = "1" ]; then
      say "building the SPA with VITE_API_BASE_URL=$API_ORIGIN"
      # This is what makes the run cross-origin. `vite build` refuses to build
      # without it (vite.config.js), which is the guard doing its job.
      ( cd "$REPO_ROOT/frontend" && VITE_API_BASE_URL="$API_ORIGIN" npm run build ) \
        > "$RUN_DIR/frontend-build.out" 2>&1 || { tail -30 "$RUN_DIR/frontend-build.out"; die "vite build failed"; }
    fi
    say "starting preview on $APP_ORIGIN (NOT vite dev)"
    # setsid: its own process group, so cleanup can take vite down with the
    # npm wrapper that spawned it. $! is then both the pid and the group id.
    setsid bash -c "cd '$REPO_ROOT/frontend' && exec npm run preview -- --port '$APP_PORT' --strictPort" \
      > "$RUN_DIR/frontend-preview.out" 2>&1 &
    PREVIEW_PID=$!
    wait_for "$APP_ORIGIN/" "preview" 60
  fi
fi

# ── Layer 1 — API suite ─────────────────────────────────────────────────────
STATUS=0
if [ "$RUN_API" = "1" ]; then
  PY="${E2E_PYTHON:-}"
  if [ -z "$PY" ]; then
    if [ -x "$REPO_ROOT/_tools/cli-venv/bin/python" ]; then PY="$REPO_ROOT/_tools/cli-venv/bin/python"
    else PY="$(command -v python3)"; fi
  fi
  "$PY" -c 'import pytest' 2>/dev/null || die "no pytest in $PY — set E2E_PYTHON to an interpreter that has it"
  say "layer 1 — API suite (pytest) against $API_ORIGIN"
  ( cd "$REPO_ROOT" && "$PY" -m pytest tests/e2e -v ) || STATUS=1
fi

# ── Layer 2 — browser suite ─────────────────────────────────────────────────
if [ "$RUN_BROWSER" = "1" ]; then
  say "layer 2 — browser suite (Playwright) against $APP_ORIGIN"
  ( cd "$REPO_ROOT/frontend" && npm run test:e2e ) || STATUS=1
fi

exit $STATUS
