-- V16__categoria_stats_flatten.sql — close-1nf-and-3nf-foundation
-- (spec "catalog-category-stats", design DD6)
--
-- categoria_stats moves from a `payload TEXT` JSON blob to 12 typed columns,
-- mirroring PriceStats.to_dict() (ml_pipeline.py:283-290) field for field.
-- The blob was itself a 1NF violation one layer removed from V7/V9's: instead
-- of a repeating group in one row, it was an entire structured record
-- serialized into a single TEXT cell, unqueryable and untyped.
--
-- n is INTEGER (a raw count, never rounded by Python). The other ten money
-- fields are BIGINT: Python's round(x) with no ndigits returns an unbounded
-- int, and fence_high on a tech category is unbounded upward — INTEGER buys
-- nothing here. cv is round(cv, 1) -> DOUBLE PRECISION. std/iqr/mad/fence_low
-- are signed on purpose (fence_low = q1 - 1.5*iqr goes negative for cheap,
-- tightly-clustered categories) — no CHECK (>= 0).
--
-- NO BACKFILL FROM payload, AND THE TABLE IS EMPTIED FIRST. Every existing
-- key is norm_cat output ("medias"), and categoria(nombre) holds the V13
-- Title-Case canon ("Medias") — an FK over the current rows would reject all
-- of them. The table is upsert-only, capped at 20 categories per run, and
-- fully regenerated by the next ML run: translating the keys is more
-- machinery than deleting them. Declared consequence: distribucionCategorias
-- is {} until the next ML run — the frontend already guards catStats?.[...]
-- at all three call sites (verified, not assumed — see docs/ARCHITECTURE.md).
--
-- The FK is VALID, NO ACTION, matching V13's fk_productos_categoria: with the
-- table emptied first, validating over zero rows costs nothing and there is
-- no reason to defer enforcement the way V4 deferred favoritos.

DELETE FROM categoria_stats;

ALTER TABLE categoria_stats
    ADD COLUMN n          INTEGER          NOT NULL DEFAULT 0,
    ADD COLUMN mean       BIGINT           NOT NULL DEFAULT 0,
    ADD COLUMN median     BIGINT           NOT NULL DEFAULT 0,
    ADD COLUMN mode       BIGINT           NOT NULL DEFAULT 0,
    ADD COLUMN std        BIGINT           NOT NULL DEFAULT 0,
    ADD COLUMN cv         DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN q1         BIGINT           NOT NULL DEFAULT 0,
    ADD COLUMN q3         BIGINT           NOT NULL DEFAULT 0,
    ADD COLUMN iqr        BIGINT           NOT NULL DEFAULT 0,
    ADD COLUMN mad        BIGINT           NOT NULL DEFAULT 0,
    ADD COLUMN fence_low  BIGINT           NOT NULL DEFAULT 0,
    ADD COLUMN fence_high BIGINT           NOT NULL DEFAULT 0;

ALTER TABLE categoria_stats DROP COLUMN payload;

ALTER TABLE categoria_stats
    ADD CONSTRAINT fk_categoria_stats_categoria
    FOREIGN KEY (categoria) REFERENCES categoria(nombre);
